### PR TITLE
Update race condition patch

### PR DESCRIPTION
**Pull request by brettpac**
This PR brings the race-condition-patch up to date with the latest noetic-devel branch from SMACC

This is a rebase operation and will likely have merge issues, so consider merging this with a new branch based on your current version of the branch noetic-devel

### CODE REVIEW

**Comment by brettpac** [comment]
Our recommended course of action:
create new branch based on noetic-devel: noetic-devel2
Then merge this pull request to the new noetic-devel2 branch

**Comment by Belal111125** [comment]
this PR has many conflicts with noetic_devel latest

**Comment by brettpac** [comment]
Ok, these are resolved.

**Comment by Belal111125** [comment]
I tried to merge it using github, I foudn this merge error:
/__w/SMACC/src/SMACC/smacc/src/smacc/signal_detector.cpp:49:5: note: to match this ‘{’
   49 |     {
      |     ^
/__w/SMACC/src/SMACC/smacc/src/smacc/signal_detector.cpp:523:1: error: expected ‘}’ at end of input
  523 | } // namespace smacc
      | ^
/__w/SMACC/src/SMACC/smacc/src/smacc/signal_detector.cpp:46:3: note: to match this ‘{’
   46 |   {
      |   ^
/__w/SMACC/src/SMACC/smacc/src/smacc/signal_detector.cpp: At global scope:
/__w/SMACC/src/SMACC/smacc/src/smacc/signal_detector.cpp:523:1: error: expected ‘}’ at end of input
  523 | } // namespace smacc
      | ^
/__w/SMACC/src/SMACC/smacc/src/smacc/signal_detector.cpp:12:1: note: to match this ‘{’
   12 | {
      | ^
make[2]: *** [SMACC/smacc/CMakeFiles/smacc.dir/build.make:154: SMACC/smacc/CMakeFiles/smacc.dir/src/smacc/signal_detector.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:3175: SMACC/smacc/CMakeFiles/smacc.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Base path: /__w/SMACC
Invoking "make -j4 -l4" failed
Source space: /__w/SMACC/src
Build space: /__w/SMACC/build
Devel space: /__w/SMACC/devel
Install space: /__w/SMACC/install
Creating symlink "/__w/SMACC/src/CMakeLists.txt" pointing to "/opt/ros/noetic/share/catkin/cmake/toplevel.cmake"
####
#### Running command: "cmake /__w/SMACC/src -DCMAKE_BUILD_TYPE=Debug -DCATKIN_DEVEL_PREFIX=/__w/SMACC/devel -DCMAKE_INSTALL_PREFIX=/__w/SMACC/install -G Unix Makefiles" in "/__w/SMACC/build"
####
####
#### Running command: "make -j4 -l4" in "/__w/SMACC/build"
####
________________________________

**Pull request merged**
